export const storeProducts = [
   {
      id:1,
      name: 'Volvo V90 T8 Twin Engine Geartronic',
      company: 'VOLVO',
      price: 519.5e3,
      modelYear: 2018,
      topSpeed: 230,
      acceleration: 5.2,
      engineType: "Plug-in Hybrid Petrol",
      power: '299kW',
      horsePower: '407hp',
      transmission: 'Automatic, 8-speed',
      numberOfDoors: '5',
      img: 'img/1.jpg',
      img1: 'img/1.1.jpg',
      img2: 'img/1.2.jpg',
      driveType: '4WD',
      chassi: 'Station Wagon',
      tankVolume: '50l',
      color: 'Beige, Black, Blue, Brown, Grey, Red, Silver, White',
      inCart: false
   },
   {
      id: 2,
      name: 'Tesla Model X Performance Single Speed',
      company: 'TESLA',
      price: 1.3e6,
      modelYear: 2019,
      topSpeed: 250,
      acceleration: 2.9,
      engineType: 'Electric',
      power: '449kW',
      horsePower: '611hp',
      transmission: 'Automatic',
      numberOfDoors: '5',
      img: 'img/2.jpg',
      img1: 'img/2.1.jpg',
      img2: 'img/2.2.jpg',
      driveType: 'AWD',
      chassi: 'SUV',
      tankVolume: '-',
      color: 'Black, Blue, Red, Silver, White',
      inCart: false
   },
   {
      id: 3,
      name: 'BMW X7 xDrive30d Steptronic',
      company: 'BMW',
      price: 989e3,
      modelYear: 2019,
      topSpeed: 227,
      acceleration: 7,
      engineType: 'Diesel',
      power: '192kW',
      horsePower: '265hp',
      transmission: 'Automatic, 8-speed',
      numberOfDoors: '5',
      img: 'img/3.jpg',
      img1: 'img/3.1.jpg',
      img2: 'img/3.2.jpg',
      driveType: 'AWD',
      chassi: 'SUV',
      tankVolume: '80l',
      color: 'Beige, Black, Blue, Brown, Grey, Silver, Violet, White',
      inCart: false
   },
   {
      id: 4,
      name: 'BMW 630i Convertible Automatic',
      company: 'BMW',
      price: 7.3e3,
      modelYear: 2008,
      topSpeed: 250,
      acceleration: 7.2,
      engineType: 'Petrol',
      power: '200kW',
      horsePower: '272hp',
      transmission: 'Automatic, 6-speed',
      numberOfDoors: '4',
      img: 'img/4.jpg',
      img1: 'img/4.1.jpg',
      img2: 'img/4.2.jpg',
      driveType: 'RWD',
      chassi: 'Cabriolet',
      tankVolume: '70l',
      color: 'Black, Blue, Grey, Red, Silver, White',
      inCart: false
   },
   {
      id: 5,
      name: 'Skoda Superb',
      company: 'SKODA',
      price: 158.9e3,
      modelYear: 2020,
      topSpeed: 250,
      acceleration: 7.2,
      engineType: 'Electric',
      power: '206kW',
      horsePower: '276hp',
      transmission: 'Automatic, Manual',
      numberOfDoors: '4, 5',
      img: 'img/5.jpg',
      img1: 'img/5.1.jpg',
      img2: 'img/5.2.jpg',
      driveType: 'RWD',
      chassi: 'Hatchback',
      tankVolume: '63l',
      color: 'Beige, Black, Blue, Brown, Green, Grey, Red, Silver, White, Yellow',
      inCart: false
   },
   {
      id: 6,
      name: 'Cadillac CTS 2.0 AWD Automatic',
      company: 'CADILLAC',
      price: 54.3e3,
      modelYear: 2016,
      topSpeed: 230,
      acceleration: 6.9,
      engineType: 'Petrol',
      power: '203kW',
      horsePower: '276hp',
      transmission: 'Automatic, 6-speed',
      numberOfDoors: '4',
      img: 'img/6.jpg',
      img1: 'img/6.1.jpg',
      img2: 'img/6.2.jpg',
      driveType: 'AWD',
      chassi: 'Sedan',
      tankVolume: '72l',
      color: 'Beige, Black, Blue, Grey, Red, Silver, White',
      inCart: false
   },
   {
      id: 7,
      name: 'Mercedes-Benz AMG GT',
      company: 'MERCEDES',
      price: 1.6e6,
      modelYear: 2020,
      topSpeed: 304,
      acceleration: 4,
      engineType: 'Petrol',
      power: '350kW',
      horsePower: '476hp',
      transmission: 'Automatic',
      numberOfDoors: '2',
      img: 'img/7.jpg',
      img1: 'img/7.1.jpg',
      img2: 'img/7.2.jpg',
      driveType: 'RWD',
      chassi: 'Coupe',
      tankVolume: '65l',
      color: 'Black, Blue, Grey, Red, White, Yellow',
      inCart: false
   },
   {
      id: 8,
      name: 'Volvo XC90 T8 Twin Engine',
      company: 'VOLVO',
      price: 598e3,
      modelYear: 2017,
      topSpeed: 230,
      acceleration: 5.6,
      engineType: 'Plug-in Hybrid Petrol',
      power: '299kW',
      horsePower: '406hp',
      transmission: 'Automatic, 8-speed',
      numberOfDoors: '4',
      img: 'img/8.jpg',
      img1: 'img/8.1.jpg',
      img2: 'img/8.2.jpg',
      driveType: 'FWDAWD',
      chassi: 'SUV',
      tankVolume: '50l',
      color: 'Beige, Black, Blue, Brown, Grey, Red, Silver, White',
      inCart: false
   },
   {
      id: 9,
      name: 'BMW Alpina B3 Touring Switch-Tronic',
      company: 'BMW',
      price: 28e3,
      modelYear: 2020,
      topSpeed: 225,
      acceleration: 5.4,
      engineType: 'Petrol',
      power: '340kW',
      horsePower: '462hp',
      transmission: 'Automatic, 8-speed',
      numberOfDoors: '5',
      img: 'img/9.jpg',
      img1: 'img/9.1.jpg',
      img2: 'img/9.2.jpg',
      driveType: '4WD',
      chassi: 'Station Wagon',
      tankVolume: '59l',
      color: 'Beige, Black, Teal, Blue, Grey, White',
      inCart: false
   },
   {
      id: 10,
      name: 'Tesla Model S P90D Single Speed',
      company: 'TESLA',
      price: 649e3,
      modelYear: 2016,
      topSpeed: 250,
      acceleration: 3.3,
      engineType: 'Electric',
      power: '376kW',
      horsePower: '511hp',
      transmission: 'Automatic',
      numberOfDoors: '5',
      img: 'img/10.jpg',
      img1: 'img/10.1.jpg',
      img2: 'img/10.2.jpg',
      driveType: '4WD',
      chassi: 'Hatchback',
      tankVolume: 'N/A',
      color: 'Black, Blue, Brown, Red, Silver, White',
      inCart: false
   },
   {
      id: 11,
      name: 'Ferrari California 30 4.3 V8 DCT',
      company: 'FERRARI',
      price: 75.3e3,
      modelYear: 2014,
      topSpeed: 312,
      acceleration: 3.8,
      engineType: 'Petrol',
      power: '360kW',
      horsePower: '490hp',
      transmission: 'Automatic, 7-speed',
      numberOfDoors: '3',
      img: 'img/11.jpg',
      img1: 'img/11.1.jpg',
      img2: 'img/11.2.jpg',
      driveType: 'RWD',
      chassi: 'Cabriolet',
      tankVolume: '48l',
      color: 'Black, Blue, Grey, Red, White, Yellow',
      inCart: false
   },
   {
      id: 12,
      name: 'BMW X6 M Competition Steptronic',
      company: 'BMW',
      price: 1.69e6,
      modelYear: 2020,
      topSpeed: 290,
      acceleration: 3.8,
      engineType: 'Petrol',
      power: '460kW',
      horsePower: '625hp',
      transmission: 'Automatic, 8-speed',
      numberOfDoors: '5',
      img: 'img/12.jpg',
      img1: 'img/12.1.jpg',
      img2: 'img/12.2.jpg',
      driveType: 'AWD',
      chassi: 'SUV',
      tankVolume: '60l',
      color: 'Black, Blue, Brown, Grey, Red, Silver, White',
      inCart: false
   },
   {
      id: 13,
      name: 'Bugatti Chiron Sport 8.0 W16 DSG Sequential',
      company: 'BUGATTI',
      price: 45e6,
      modelYear: 2020,
      topSpeed: 420,
      acceleration: 2.5,
      engineType: 'Petrol',
      power: '1119kW',
      horsePower: '1521hp',
      transmission: 'Automatic, 7-speed',
      numberOfDoors: '2',
      img: 'img/13.jpg',
      img1: 'img/13.1.jpg',
      img2: 'img/13.2.jpg',
      driveType: '4WD',
      chassi: 'Coupe',
      tankVolume: '100l',
      color: 'N/A',
      inCart: false
   },
   {
      id: 14,
      name: 'Nissan GT-R Nismo 3.8 V6 4x4 DCT',
      company: 'NISSAN',
      price: 995e3,
      modelYear: 2020,
      topSpeed: 315,
      acceleration: 3.1,
      engineType: 'Petrol',
      power: '447kW',
      horsePower: '608hp',
      transmission: 'Automatic, 6-speed',
      numberOfDoors: '2',
      img: 'img/14.jpg',
      img1: 'img/14.1.jpg',
      img2: 'img/14.2.jpg',
      driveType: 'AWD',
      chassi: 'Coupe',
      tankVolume: '74l',
      color: 'N/A',
      inCart: false
   },
   {
      id: 15,
      name: 'McLaren 650S Spider SSG',
      company: 'MCLAREN',
      price: 120e3,
      modelYear: 2014,
      topSpeed: 320,
      acceleration: 3.5,
      engineType: 'Petrol',
      power: '478kW',
      horsePower: '650hp',
      transmission: 'Automatic, 7-speed',
      numberOfDoors: '2',
      img: 'img/15.jpg',
      img1: 'img/15.1.jpg',
      img2: 'img/15.2.jpg',
      driveType: 'RWD',
      chassi: 'Cabriolet',
      tankVolume: '72l',
      color: 'Black, Blue, Green, Grey, Orange, Red, Silver, White',
      inCart: false
   },
   {
      id: 16,
      name: 'Jaguar F-Type R AWD Automatic',
      company: 'JAGUAR',
      price: 102e3,
      modelYear: 2016,
      topSpeed: 300,
      acceleration: 4.1,
      engineType: 'Petrol',
      power: '405kW',
      horsePower: '550hp',
      transmission: 'Automatic, 8-speed',
      numberOfDoors: '2',
      img: 'img/16.jpg',
      img1: 'img/16.1.jpg',
      img2: 'img/16.2.jpg',
      driveType: 'AWD',
      chassi: 'Coupe',
      tankVolume: '70l',
      color: 'Black, Blue, Green, Grey, Orange, Red, Silver, White',
      inCart: false
   },
   {
      id: 17,
      name: 'BMW M4 Convertible Manual',
      company: 'BMW',
      price: 55.4e3,
      modelYear: 2016,
      topSpeed: 250,
      acceleration: 4.6,
      engineType: 'Petrol',
      power: '317kW',
      horsePower: '431hp',
      transmission: 'Automatic, 6-speed',
      numberOfDoors: '2',
      img: 'img/17.jpg',
      img1: 'img/17.1.jpg',
      img2: 'img/17.2.jpg',
      driveType: '4WD',
      chassi: 'Cabriolet',
      tankVolume: '60l',
      color: 'Black, Blue, Grey, Orange, Red, Silver, White, Yellow',
      inCart: false
   },
   {
      id: 18,
      name: 'Porsche Cayenne E-Hybrid TipTronic S',
      company: 'PORSCHE',
      price: 999.9e3,
      modelYear: 2019,
      topSpeed: 253,
      acceleration: 5,
      engineType: 'Plug-in Hybrid Petrol',
      power: '340kW',
      horsePower: '462hp',
      transmission: 'Automatic, 8-speed',
      numberOfDoors: '5',
      img: 'img/18.jpg',
      img1: 'img/18.1.jpg',
      img2: 'img/18.2.jpg',
      driveType: 'AWD',
      chassi: 'SUV',
      tankVolume: '75l',
      color: 'Beige, Black, Blue, Brown, Grey, Silver, White',
      inCart: false
   },
   {
      id: 19,
      name: 'Mercedes-Benz AMG C 63 S Coupé',
      company: 'MERCEDES',
      price: 875.5e3,
      modelYear: 2019,
      topSpeed: 290,
      acceleration: 3.9,
      engineType: 'Petrol',
      power: '375kW',
      horsePower: '510hp',
      transmission: 'Automatic, 9-speed',
      numberOfDoors: '2',
      img: 'img/19.jpg',
      img1: 'img/19.1.jpg',
      img2: 'img/19.2.jpg',
      driveType: 'RWD',
      chassi: 'Coupe',
      tankVolume: '66l',
      color: 'Black, Blue, Green, Grey, Red, Silver, White',
      inCart: false
   },
   {
      id: 20,
      name: 'Audi A7 Sportback 55 TFSI quattro S Tronic',
      company: 'AUDI',
      price: 609.9e3,
      modelYear: 2019,
      topSpeed: 250,
      acceleration: 5.3,
      engineType: 'Petrol',
      power: '250kW',
      horsePower: '340hp',
      transmission: 'Automatic, 7-speed',
      numberOfDoors: '5',
      img: 'img/20.jpg',
      img1: 'img/20.1.jpg',
      img2: 'img/20.2.jpg',
      driveType: 'AWD',
      chassi: 'Hatchback',
      tankVolume: '63l',
      color: 'Beige, Black, Blue, Brown, Green, Grey, Red, Silver, White',
      inCart: false
   },
   {
      id: 21,
      name: 'Audi Q5 40 TDI quattro S Tronic',
      company: 'AUDI',
      price: 404.4e3,
      modelYear: 2019,
      topSpeed: 218,
      acceleration: 8.1,
      engineType: 'Diesel',
      power: '140kW',
      horsePower: '190hp',
      transmission: 'Automatic, 7-speed',
      numberOfDoors: '5',
      img: 'img/21.jpg',
      img1: 'img/21.1.jpg',
      img2: 'img/21.2.jpg',
      driveType: 'AWD',
      chassi: 'SUV',
      tankVolume: '65l',
      color: 'Black, Blue, Brown, Green, Grey, Red, Silver, White',
      inCart: false
   },
   {
      id: 22,
      name: 'Renault Talisman Grandtour 1.6 TCe EDC',
      company: 'RENAULT',
      price: 148.3e3,
      modelYear: 2017,
      topSpeed: 215,
      acceleration: 9.6,
      engineType: 'Petrol',
      power: '110kW',
      horsePower: '150hp',
      transmission: 'Automatic, 7-speed',
      numberOfDoors: '5',
      img: 'img/22.jpg',
      img1: 'img/22.1.jpg',
      img2: 'img/22.2.jpg',
      driveType: 'FWD',
      chassi: 'Station Wagon',
      tankVolume: '51l',
      color: 'Beige, Black, Blue, Brown, Green, Grey, Red, White',
      inCart: false
   },
   {
      id: 23,
      name: 'Mazda 6 Sedan 2.5 SKYACTIV-G Automatic',
      company: 'MAZDA',
      price: 153.1e3,
      modelYear: 2016,
      topSpeed: 223,
      acceleration: 7.8,
      engineType: 'Petrol',
      power: '141kW',
      horsePower: '192hp',
      transmission: 'Automatic, 7-speed',
      numberOfDoors: '4',
      img: 'img/23.jpg',
      img1: 'img/23.1.jpg',
      img2: 'img/23.2.jpg',
      driveType: 'FWD',
      chassi: 'Sedan',
      tankVolume: '62l',
      color: 'Black, Blue, Brown, Grey, Red, Silver, White',
      inCart: false
   },
   {
      id: 24,
      name: 'Mazda 3 Sport 2.0 SKYACTIV-G Automatic',
      company: 'MAZDA',
      price: 157.4e3,
      modelYear: 2018,
      topSpeed: 194,
      acceleration: 10.4,
      engineType: 'Petrol',
      power: '88kW',
      horsePower: '120hp',
      transmission: 'Automatic, 6-speed',
      numberOfDoors: '5',
      img: 'img/24.jpg',
      img1: 'img/24.1.jpg',
      img2: 'img/24.2.jpg',
      driveType: 'FWD',
      chassi: 'Hatchback',
      tankVolume: '51l',
      color: 'Black, Blue, Brown, Silver, Grey, Red, White',
      inCart: false
   },
]

export const detailProduct = {
      id:1,
      name: 'Volvo V90 T8 Twin Engine Geartronic',
      company: 'VOLVO',
      price: 519.5e3,
      modelYear: 2018,
      topSpeed: 230,
      acceleration: 5.2,
      engineType: "Plug-in Hybrid Petrol",
      power: '299kW',
      horsePower: '407hp',
      transmission: 'Automatic, 8-speed',
      numberOfDoors: '5',
      img: 'img/1.jpg',
      img1: 'img/1.1.jpg',
      img2: 'img/1.2.jpg',
      driveType: '4WD',
      chassi: 'Station Wagon',
      tankVolume: '50l',
      color: 'Beige, Black, Blue, Brown, Grey, Red, Silver, White',
      inCart: false
   }
